import { Address, BeneficiaryOwner, MaritalStatus } from '..';
import { Dir, DirCountry } from './directory';
import { SelfEmployment, SelfEmploymentDto } from './self-employment';

import { Employment } from './employment';
import { IdentityCard } from '@app/_models';
import { StaticDirectory } from '@app/_models';

export class Applicant {
  applicationId: number;
  affiliated: boolean;
  approvedIncome: number;
  attFailed: number;
  beneficiaryOwner: BeneficiaryOwner;
  birthAddressObj: Address;
  birthDate: string;
  birthPlace: string;
  childrenUnder18: number;
  citizenship: DirCountry;
  doubleCitizenship: DirCountry;
  comment: string;
  created: string;
  dboAgreement: boolean;
  dirAccommodationType: Dir;
  dirEducation: Dir;
  email: string;
  employment: Employment;
  facebookId: string;
  facebookLanguage: string;
  factAddress: string;
  factAddressObj: Address;
  firstName: string;
  fullFormIncome: number;
  gender: StaticDirectory;
  generatedCode: string;
  homePhone: string;
  id: number;
  identityCard: IdentityCard;
  integrationInterfaceId: number;
  isAddIncome: boolean;
  isAmlNeeded: boolean;
  isApplicantStopList: boolean;
  isCreditHistory: boolean;
  isIpdl: boolean;
  isIpdlRelative: boolean;
  isIpldOperation: boolean;
  isOverdue6: boolean;
  isRealEqFactAddress: boolean;
  isResident: boolean;
  isUsaResident: boolean;
  lastName: string;
  maritalStatus: MaritalStatus;
  maxAttGenerate: number;
  maxAttInput: number;
  middleName: string;
  militaryDuty: StaticDirectory;
  mobileContactCommunicationType: Dir;
  mobilePhone: string;
  mobilePhoneCommunicationType: Dir;
  numberOfEnrolment: number;
  postAddress: string;
  postAddressObj: Address;
  receivedCode: string;
  regAddress: string;
  regAddressObj: Address;
  selfEmployment: SelfEmployment;
  timeoutGenerate: number;
  timeoutInput: number;
  shortFormIncome: number;
  spouseFirstName: string;
  spouseLastName: string;
  spousePin: string;
  totalIncome: number;
  totalJobExp: number;
  updated: string;
  absCustomerId: number;
  decisionMakingIncome: number;
}

export class ApplicantDto {
  applicationId: number;
  affiliated: boolean;
  approvedIncome: number;
  beneficiaryOwnerDto: BeneficiaryOwner;
  birthAddressObj: Address;
  birthDate: string;
  birthPlace: string;
  childrenUnder18: number;
  citizenshipId: number;
  doubleCitizenshipId: number;
  comment: string;
  created: string;
  dboAgreement: boolean;
  dirAccommodationTypeId: number;
  educationId: number;
  email: string;
  employmentId: number;
  facebookId: string;
  facebookLanguage: string;
  factAddress: string;
  factAddressObj: Address;
  firstName: string;
  fullFormIncome: number;
  genderId: number;
  homePhone: string;
  id: number;
  identityCardId: number;
  integrationInterfaceId: number;
  isAddIncome: boolean;
  isAmlNeeded: boolean;
  isApplicantStopList: boolean;
  isCreditHistory: boolean;
  isIpdl: boolean;
  isIpdlRelative: boolean;
  isIpldOperation: boolean;
  isOverdue6: boolean;
  isRealEqFactAddress: boolean;
  isResident: boolean;
  isUsaResident: boolean;
  lastName: string;
  maritalStatusId: number;
  middleName: string;
  militaryDutyId: number;
  mobileContactCommunicationTypeId: number;
  mobilePhone: string;
  mobilePhoneCommunicationTypeId: number;
  numberOfEnrolment: number;
  photo: string;
  photoBranch: string;
  postAddress: string;
  postAddressObj: Address;
  regAddress: string;
  regAddressObj: Address;
  selfEmployment: SelfEmploymentDto;
  shortFormIncome: number;
  spouseFirstName: string;
  spouseLastName: string;
  spousePin: string;
  totalIncome: number;
  totalJobExp: number;
  updated: string;
  absCustomerId: number;
  decisionMakingIncome: number;

  constructor(obj: Applicant) {
    this.applicationId = obj.applicationId;
    this.affiliated = obj.affiliated;
    this.approvedIncome = obj.approvedIncome;
    this.beneficiaryOwnerDto = obj.beneficiaryOwner;
    this.birthAddressObj = obj.birthAddressObj;
    this.birthDate = obj.birthDate;
    this.birthPlace = obj.birthPlace;
    this.childrenUnder18 = obj.childrenUnder18;
    this.citizenshipId = obj.citizenship ? obj.citizenship.id : null;
    this.doubleCitizenshipId = obj.doubleCitizenship ? obj.doubleCitizenship.id : null;
    this.comment = obj.comment;
    this.created = obj.created;
    this.updated = obj.updated;
    this.dboAgreement = obj.dboAgreement;
    this.dirAccommodationTypeId = obj.dirAccommodationType ? obj.dirAccommodationType.id : null;
    this.educationId = obj.dirEducation ? obj.dirEducation.id : null;
    this.email = obj.email;
    this.employmentId = obj.employment ? obj.employment.id : null;
    this.facebookId = obj.facebookId;
    this.facebookLanguage = obj.facebookLanguage;
    this.factAddress = obj.factAddress;
    this.factAddressObj = obj.factAddressObj;
    this.firstName = obj.firstName;
    this.fullFormIncome = obj.fullFormIncome;
    this.genderId = obj.gender ? +obj.gender.id : null;
    this.homePhone = obj.homePhone;
    this.id = obj.id;
    this.identityCardId = obj.identityCard ? obj.identityCard.id : null;
    this.integrationInterfaceId = obj.integrationInterfaceId;
    this.isApplicantStopList = obj.isApplicantStopList;
    this.isAddIncome = obj.isAddIncome;
    this.isAmlNeeded = obj.isAmlNeeded;
    this.isCreditHistory = obj.isCreditHistory;
    this.isIpdl = obj.isIpdl;
    this.isIpdlRelative = obj.isIpdlRelative;
    this.isIpldOperation = obj.isIpldOperation;
    this.isOverdue6 = obj.isOverdue6;
    this.isRealEqFactAddress = obj.isRealEqFactAddress;
    this.isResident = obj.isResident;
    this.isUsaResident = obj.isUsaResident;
    this.lastName = obj.lastName;
    this.maritalStatusId = obj.maritalStatus ? +obj.maritalStatus.id : null;
    this.middleName = obj.middleName;
    this.militaryDutyId = obj.militaryDuty ? +obj.militaryDuty.id : null;
    this.mobileContactCommunicationTypeId = obj.mobileContactCommunicationType
      ? obj.mobileContactCommunicationType.id
      : null;
    this.mobilePhone = obj.mobilePhone;
    this.mobilePhoneCommunicationTypeId = obj.mobilePhoneCommunicationType ? obj.mobilePhoneCommunicationType.id : null;
    this.numberOfEnrolment = obj.numberOfEnrolment;
    this.postAddress = obj.postAddress;
    this.postAddressObj = obj.postAddressObj;
    this.regAddress = obj.regAddress;
    this.regAddressObj = obj.regAddressObj;
    this.shortFormIncome = obj.shortFormIncome;
    this.spouseFirstName = obj.spouseFirstName;
    this.spouseLastName = obj.spouseLastName;
    this.spousePin = obj.spousePin;
    this.totalIncome = obj.totalIncome;
    this.totalJobExp = obj.totalJobExp;
    this.absCustomerId = obj.absCustomerId;
    this.decisionMakingIncome = obj.decisionMakingIncome;
  }
}
