export class CreditInfoResponseDto {
  applicantId: number;
  applicationId: number;
  batchId: number;
  birthDate: string;
  borrowerClassification: string;
  creditInfoContracts: CreditInfoContractDto[];
  firstName: string;
  gender: string;
  georgianCitizen: string;
  guid: string;
  id: number;
  inquiriesLast12Month: number;
  inquiriesLast1Month: number;
  inquiriesLast3Month: number;
  inquiriesLast6Month: number;
  lastUpdate: string;
  logGuid: string;
  nationalId: string;
  probabilityOfDefault: number;
  reportIssueDate: string | Date;
  reportStatus: string;
  request: string;
  response: string;
  riskGrade: string;
  rqDate: string | Date;
  rsDate: string | Date;
  score: number;
  statusCode: string;
  statusMessage: string;
  statusName: string;
  surname: string;
}

export class CreditInfoContractDto {
  brmsMonthlyPayment: number;
  contractCode: string;
  contractIdentifier: string;
  contractTerm: number;
  created: string | Date;
  creditCurrency: string;
  creditInfoContractGuarantees: CreditInfoContractGuaranteeDto[];
  creditInfoContractHistoryRecords: CreditInfoContractHistoryRecordDto[];
  creditInfoContractSubjects: CreditInfoContractSubjectDto[];
  creditLimitAmount: number;
  creditLimitAmountCurrency: string;
  creditPurpose: string;
  creditUsedInMonth: string;
  creditor: string;
  currentAccruedPenaltyAmount: number;
  currentAccruedPenaltyCurrency: string;
  currentOutstandingPrincipalAmount: number;
  currentOutstandingPrincipalCurrency: string;
  currentOverdueInterestAndCommissionAmount: number;
  currentOverdueInterestAndCommissionCurrency: string;
  currentOverduePrincipalAmount: number;
  currentOverduePrincipalCurrency: string;
  currentStatus: string;
  currentUndisbursedLoanAmount: number;
  currentUndisbursedLoanAmountCurrency: string;
  daysInDeliquency: number;
  deliqDays3059: number;
  deliqDays3059InLast180: number;
  deliqDays6089: number;
  deliqDays6089InLast180: number;
  deliqDaysGt90InLast180: number;
  deliqSaysGt90: number;
  expectedEndDate: string | Date;
  id: number;
  isRefAvailable: boolean;
  loanPartiallySecuredByDeposit: string;
  loanType: string;
  maximumAmountOfInstalmentBySchedule: number;
  maximumAmountOfInstalmentByScheduleCurrency: string;
  maximumNumberOfDelinquencyDays: number;
  outstandingAmount: number;
  outstandingAmountCurrency: string;
  outstandingInstalmentsCount: number;
  overdueAmount: number;
  overdueAmountCurrency: string;
  overdueInstalmentsCount: number;
  penaltyPaid: number;
  penaltyPaidCurrency: string;
  penaltySum: number;
  penaltySumCurrency: string;
  phaseOfOperation: string;
  remainingTerm: number;
  repaymentType: string;
  role: string;
  roleOfClient: string;
  selected: boolean;
  standardInstalmentAmount: number;
  standardInstalmentAmountCurrency: string;
  startDate: string | Date;
  status: string;
  totalCreditAmount: number;
  totalCreditAmountCurrency: string;
  totalNumberOfDelinquencyDays: number;
  totalNumberOfDelinquencyDaysInLastYear: number;
  totalNumberOfOverdueInstalments: number;
  type: string;
  updated: string | Date;
  usedAmount: number;
  usedAmountCurrency: string;
}

export class CreditInfoContractHistoryRecordDto {
  created: string | Date;
  creditLimitAmount: number;
  creditLimitAmountCurrency: string;
  creditUsedInMonth: string;
  currentOutstandingPrincipalAmount: number;
  currentOutstandingPrincipalCurrency: string;
  currentOverduePrincipalAmount: number;
  currentOverduePrincipalCurrency: string;
  id: number;
  key: string;
  month: number;
  outstandingAmount: number;
  outstandingAmountCurrency: string;
  overdueAmount: number;
  overdueAmountCurrency: string;
  overdueDays: number;
  overdueInstalmentsCount: number;
  penaltyPaid: number;
  penaltyPaidCurrency: string;
  penaltySum: number;
  penaltySumCurrency: string;
  totalCreditAmount: number;
  totalCreditAmountCurrency: string;
  type: string;
  updated: string | Date;
  usedAmount: number;
  usedAmountCurrency: string;
  year: number;
}

export class CreditInfoContractGuaranteeDto {
  guaranteeAmount: string;
  guaranteeCurrency: string;
  guaranteeKey: string;
  guaranteeType: string;
  id: number;
}

export class CreditInfoContractSubjectDto {
  firstName: string;
  guaranteeAmount: number;
  guaranteeCurrency: string;
  lastName: string;
  pin: string;
  roleOfClient: string;
}
