import { Dir, DirAbsCode, Directory, DirSalesChannel } from './directory';

import { Segment } from './segment';
import { ProductToPaymentDay } from '@app/_models/api-models/product-to-payment-day';
import {DirAccountProduct} from "@app/_models/api-models/dir-account-product";
import {DirScheduleType} from "@app/_models/api-models/dir-schedule-type";
import {DirScheduleFrequency} from "@app/_models/api-models/dir-schedule-frequency";

export class Product {
  absCode: string;
  absId: string;
  active: boolean;
  cardAccountProduct: DirAccountProduct;
  changedByUsername: string;
  channels: DirSalesChannel[];
  code: string;
  created: string | Date;
  currAccountProduct: DirAccountProduct;
  cutOffScore: number;
  dateFrom: string | Date;
  dateTo: string | Date;
  forCard: boolean;
  forRef: boolean;
  highCoefLess1000: number;
  highCoefMore1000: number;
  id: number;
  instAccountProduct: DirAccountProduct;
  isComRestr: boolean;
  isCurrentAccount: boolean;
  isExistingCard: boolean;
  isForcedRestr: boolean;
  isInsurance: boolean;
  isOverdraft: boolean;
  isUniqueProduct: boolean;
  isVisibleOnline: boolean;
  lowCoefLess1000: number;
  lowCoefMore1000: number;
  nameEn: string;
  nameGe: string;
  nameRu: string;
  paymentDays: ProductToPaymentDay[];
  productGroupId: string;
  scheduleFreq: DirScheduleFrequency[];
  scheduleTypes: DirScheduleType[];
  scoringType: number;
  segments: Segment[];
  updated: string | Date;
}

export class ProductRes extends Dir {
  absCode: string;
  absId: string;
  channels: DirSalesChannel[];
  cardAccountProduct: DirAbsCode;
  currAccountProduct: DirAbsCode;
  cutOffScore: number;
  dateFrom: string | Date;
  dateTo: string | Date;
  forCard: boolean;
  forRef: boolean;
  highCoefLess1000: number;
  highCoefMore1000: number;
  instAccountProduct: DirAbsCode;
  isComRestr: boolean;
  isCurrentAccount: boolean;
  isExistingCard: boolean;
  isForcedRestr: boolean;
  isInsurance: boolean;
  isOverdraft: boolean;
  isUniqueProduct: boolean;
  isVisibleOnline: boolean;
  lowCoefLess1000: number;
  lowCoefMore1000: number;
  paymentDays: ProductToPaymentDay[];
  productGroupId: string;
  scheduleFreq: Dir[];
  scheduleTypes: DirAbsCode[];
  scoringType: number;
  segments: Segment[];
}

export class ProductResDto {
  absCode: string;
  absId: string;
  active: boolean;
  cardAccountProduct: DirAbsCode;
  currAccountProduct: DirAbsCode;
  cutOffScore: number;
  changedByUsername: string;
  channels: Directory[];
  code: string;
  created: string | Date;
  dateFrom: string | Date;
  dateTo: string | Date;
  forCard: boolean;
  forRef: boolean;
  highCoefLess1000: number;
  highCoefMore1000: number;
  instAccountProduct: DirAbsCode;
  id: number;
  isComRestr: boolean;
  isCurrentAccount: boolean;
  isExistingCard: boolean;
  isForcedRestr: boolean;
  isInsurance: boolean;
  isOverdraft: boolean;
  isUniqueProduct: boolean;
  isVisibleOnline: boolean;
  lowCoefLess1000: number;
  lowCoefMore1000: number;
  nameGe: string;
  nameEn: string;
  nameRu: string;
  paymentDays: ProductToPaymentDay[];
  productGroupId: string;
  scheduleFreq: Dir[];
  scheduleTypes: DirAbsCode[];
  scoringType: number;
  segments: Segment[];
  updated: string | Date;

  constructor(productRes: ProductRes) {
    this.absCode = productRes.absCode;
    this.absId = productRes.absId;
    this.active = productRes.active;
    this.cardAccountProduct = productRes.cardAccountProduct;
    this.currAccountProduct = productRes.currAccountProduct;
    this.cutOffScore = productRes.cutOffScore;
    this.changedByUsername = productRes.changedByUsername;
    this.channels = productRes.channels;
    this.code = productRes.code;
    this.created = productRes.created;
    this.dateFrom = productRes.dateFrom;
    this.dateTo = productRes.dateTo;
    this.forCard = productRes.forCard;
    this.forRef = productRes.forRef;
    this.highCoefLess1000 = productRes.highCoefLess1000;
    this.highCoefMore1000 = productRes.highCoefMore1000;
    this.instAccountProduct = productRes.instAccountProduct;
    this.id = productRes.id;
    this.isComRestr = productRes.isComRestr;
    this.isCurrentAccount = productRes.isCurrentAccount;
    this.isExistingCard = productRes.isExistingCard;
    this.isForcedRestr = productRes.isForcedRestr;
    this.isInsurance = productRes.isInsurance;
    this.isOverdraft = productRes.isOverdraft;
    this.isUniqueProduct = productRes.isUniqueProduct;
    this.isVisibleOnline = productRes.isVisibleOnline;
    this.lowCoefLess1000 = productRes.lowCoefLess1000;
    this.lowCoefMore1000 = productRes.lowCoefMore1000;
    this.nameGe = productRes.nameGe;
    this.nameEn = productRes.nameEn;
    this.nameRu = productRes.nameRu;
    this.paymentDays = productRes.paymentDays;
    this.productGroupId = productRes.productGroupId;
    this.scheduleFreq = productRes.scheduleFreq;
    this.scheduleTypes = productRes.scheduleTypes;
    this.scoringType = productRes.scoringType;
    this.segments = productRes.segments;
    this.updated = productRes.updated;
  }
}

export class EmptyProductResDto {
  absCode: string = null;
  absId: string = null;
  active: boolean = null;
  cardAccountProduct: DirAbsCode = null;
  currAccountProduct: DirAbsCode = null;
  cutOffScore: number = null;
  changedByUsername: string = null;
  channels: DirSalesChannel[] = [];
  code: string = null;
  created: string | Date = null;
  dateFrom: string | Date = null;
  dateTo: string | Date = null;
  forCard: boolean = null;
  forRef: boolean = null;
  highCoefLess1000: number = null;
  highCoefMore1000: number = null;
  instAccountProduct: DirAbsCode = null;
  id: number = null;
  isComRestr: boolean = null;
  isCurrentAccount: boolean = null;
  isExistingCard: boolean = null;
  isInsurance: boolean = null;
  isVisibleOnline: boolean = null;
  isForcedRestr: boolean = null;
  isOverdraft: boolean = null;
  isUniqueProduct: boolean = null;
  lowCoefLess1000: number = null;
  lowCoefMore1000: number = null;
  nameGe: string = null;
  nameEn: string = null;
  nameRu: string = null;
  paymentDays: ProductToPaymentDay[] = [];
  productGroupId: string = null;
  scheduleFreq: Dir[] = [];
  scheduleTypes: DirAbsCode[] = [];
  segments: Segment[] = [];
  scoringType: number = null;
  updated: string | Date = null;
}
